openapi: "3.0.3"
info:
  title: "OpenAPI definition"
  description: "brevis API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
    description: "Generated server url"
paths:
  /brevis:
    post:
      tags:
        - "brevis-resource"
      operationId: "create"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BrevisCreateDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BrevisDto"
  /brevis/{shorturl}:
    get:
      tags:
        - "brevis-resource"
      operationId: "getOne"
      parameters:
        - name: "shorturl"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BrevisDto"
components:
  schemas:
    BrevisCreateDTO:
      type: "object"
      properties:
        sourceURL:
          type: "string"
    BrevisDto:
      type: "object"
      properties:
        sourceURL:
          type: "string"
        shortURL:
          type: "string"